Upgrade version of Leiningen (cherry picked from commit 0e06b8b2221ca6cdaf4c9c6830b4fcafed186c77)

diff --git a/bin/lein b/bin/lein
--- a/bin/lein
+++ b/bin/lein
@@ -1,7 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-LEIN_VERSION="1.6.2"
-export LEIN_VERSION
+export LEIN_VERSION="1.7.0"
 
 case $LEIN_VERSION in
     *SNAPSHOT) SNAPSHOT="YES" ;;
@@ -35,18 +34,23 @@ done
 if [ "$LEIN_HOME" = "" ]; then
   if [ -d "$PWD/.lein" ] && [ "$PWD" != "$HOME" ]; then
     echo "Leiningen is running in bundled mode."
-    LEIN_HOME="$PWD/.lein"
+    export LEIN_HOME="$PWD/.lein"
   else
-    LEIN_HOME="$HOME/.lein"
+    export LEIN_HOME="$HOME/.lein"
   fi
 fi
 
-DEV_PLUGINS="$(ls -1 lib/dev/*jar 2> /dev/null)"
+DEV_PLUGINS="$(ls -1 lib/dev/*jar .lein-plugins/*jar 2> /dev/null)"
 USER_PLUGINS="$(ls -1 "$LEIN_HOME"/plugins/*jar 2> /dev/null)"
 
 artifact_name () {
-    echo "$1" | sed -e "s/.*\/\(.*\)/\1/" | \
-        rev | sed -e "s/raj[-[:digit:].]*-\(.*\)/\1/" | rev
+    which rev > /dev/null
+    if [ $? -eq 0 ]; then
+        echo "$1" | sed -e "s/.*\/\(.*\)/\1/" | \
+            rev | sed -e "s/raj[-[:digit:].]*-\(.*\)/\1/" | rev
+    else
+        echo "$1"
+    fi
 }
 
 unique_user_plugins () {
@@ -129,10 +133,25 @@ if type -p curl >/dev/null 2>&1; then
     HTTP_CLIENT="curl $CURL_PROXY --insecure -f -L -o"
 fi
 
+# If we don't have Leiningen's own Clojure on the bootclasspath, boot
+# will be slower, and versions of Clojure in :dev-dependencies can
+# take precedence.
+if [ ! -r "$CLOJURE_JAR" ]; then
+    CLOJURE_JAR_URL=http://build.clojure.org/releases/org/clojure/clojure/1.2.1/clojure-1.2.1.jar
+    CLOJURE_HASH="be088d20c078ce48d42afba05984f1ef7c02142b"
+    mkdir -p "$(dirname $CLOJURE_JAR)"
+    $HTTP_CLIENT $CLOJURE_JAR $CLOJURE_JAR_URL
+    if [ "`sha1sum $CLOJURE_JAR | cut -f 1 -d \" \"`" != "$CLOJURE_HASH" ]; then
+        echo "WARNING: Clojure jar failed to download from $CLOJURE_JAR_URL"
+    fi
+fi
+
 export JAVA_CMD=${JAVA_CMD:-"java"}
+export LEIN_JAVA_CMD=${LEIN_JAVA_CMD:-$JAVA_CMD}
 
 # Support $JAVA_OPTS for backwards-compatibility.
-export JVM_OPTS=${JVM_OPTS:-"$JAVA_OPTS"}
+export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"
+export LEIN_JVM_OPTS=${LEIN_JVM_OPTS:-$JVM_OPTS}
 
 # TODO: investigate http://skife.org/java/unix/2011/06/20/really_executable_jars.html
 # If you're packaging this for a package manager (.deb, homebrew, etc)
@@ -206,8 +225,7 @@ else
     fi
 
     JLINE=""
-    if ([ "$1" = "repl" ] || [ "$1" = "interactive" ] || [ "$1" = "int" ]) &&
-        [ -z $INSIDE_EMACS ] && [ "$TERM" != "dumb" ]; then
+    if [ -z $INSIDE_EMACS ] && [ "$TERM" != "dumb" ]; then
         # Use rlwrap if it's available, otherwise fall back to JLine
         RLWRAP=`which rlwrap`
         if [ ! -x "$RLWRAP" ] || [ "$RLWRAP" = "" ]; then
@@ -227,33 +245,47 @@ else
             if [ $? -eq 0 ]; then
                 RLWRAP="$RLWRAP -r -m -q '\"'"
             fi
+            # see if there is a clojure-completion-file
+            RLWRAP_CLJ_WORDS_FILE=${RLWRAP_CLJ_WORDS_FILE:-"${HOME}/.clj_completions"}
+            RLWRAP_CLJ_WORDS_OPTION=""
+            if [ -r "${RLWRAP_CLJ_WORDS_FILE}" ]; then
+                RLWRAP_CLJ_WORDS_OPTION="-f ${RLWRAP_CLJ_WORDS_FILE}";
+            fi
+            RLWRAP="${RLWRAP} $RLWRAP_OPTIONS -b \"(){}[],^%$#@\";:'\" ${RLWRAP_CLJ_WORDS_OPTION}"
         fi
+    fi
+
+    test $CYGWIN_JLINE && stty -icanon min 1 -echo
+
+    TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
+    if [ "$OSTYPE" = "cygwin" ]; then
+        TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
     fi
 
     # The -Xbootclasspath argument is optional here: if the jar
     # doesn't exist everything will still work, it will just have a
     # slower JVM boot.
-    test $CYGWIN_JLINE && stty -icanon min 1 -echo
-    if [ "$1" = "trampoline" ]; then
-        TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
-        if [ "$OSTYPE" = "cygwin" ]; then
-            TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
-        fi
-        $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client \
-            $LEIN_JVM_OPTS -Dleiningen.original.pwd="$ORIGINAL_PWD" \
-            -Dleiningen.trampoline-file=$TRAMPOLINE_FILE -cp "$CLASSPATH" \
-            $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
-            $NULL_DEVICE "$@"
-        if [ -r $TRAMPOLINE_FILE ]; then
-            TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
-            rm $TRAMPOLINE_FILE
-            exec sh -c "exec $TRAMPOLINE"
-        fi
+
+    ## TODO: -XX:+UseCompressedOops only works on 64 bit jvm
+    # is there some way of detecting 64bit at this stage? - tavisrudd
+    $RLWRAP $LEIN_JAVA_CMD \
+        -Xbootclasspath/a:"$CLOJURE_JAR" \
+        -client $LEIN_JVM_OPTS \
+        -XX:+TieredCompilation \
+        -Dleiningen.original.pwd="$ORIGINAL_PWD" \
+        -Dleiningen.trampoline-file=$TRAMPOLINE_FILE \
+        -cp "$CLASSPATH" \
+        $JLINE clojure.main \
+        -e "(use 'leiningen.core)(-main)" \
+        $NULL_DEVICE "$@"
+    EXIT_CODE=$?
+
+    if [ -r $TRAMPOLINE_FILE ]; then
+        TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
+        rm $TRAMPOLINE_FILE
+        exec sh -c "exec $TRAMPOLINE"
     else
-        exec $RLWRAP $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client \
-            $LEIN_JVM_OPTS -Dleiningen.original.pwd="$ORIGINAL_PWD" \
-            -cp "$CLASSPATH" $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
-            $NULL_DEVICE "$@"
+        test $CYGWIN_JLINE && stty icanon echo
+        exit $EXIT_CODE
     fi
-    test $CYGWIN_JLINE && stty icanon echo
 fi
